name: CI

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Cache node modules
        uses: actions/cache@v4.0.1
        with:
          path: node_modules
          key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            node-cache-${{ runner.OS }}-yarn-
            node-cache-${{ runner.OS }}-
      - name: Install dependencies
        run: |
          yarn --immutable
      - name: Run unit and integration tests
        run: yarn test:ci
  # lint:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Cache node modules
  #       uses: actions/cache@v4.0.1
  #       with:
  #         path: node_modules
  #         key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           node-cache-${{ runner.OS }}-yarn-
  #           node-cache-${{ runner.OS }}-
  #     - name: Run Linter
  #       run: yarn run lint
  # unit-test:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #     - name: Cache node modules
  #       uses: actions/cache@v4.0.1
  #       with:
  #         path: node_modules
  #         key: node-cache-${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
  #         restore-keys: |
  #           node-cache-${{ runner.OS }}-yarn-
  #           node-cache-${{ runner.OS }}-
  #     - name: Run unit and integration tests
  #       run: yarn test:ci
  #     - name: Test coveralls
  #       uses: coverallsapp/github-action@3dfc5567390f6fa9267c0ee9c251e4c8c3f18949 # v2.2.3
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}
